### ISSUE TITLE
Naming is confusing with cargo-audit

### ISSUE THREAD

**Issue by nastevens** [Shnatsel/rust-audit#1]
`cargo-audit` already has decent developer penetration, so having another `audit` crate is confusing. Could I maybe suggest the name `rust-traceable` instead?

**Comment by Shnatsel** [comment]
This is somewhat intentional because it's meant to be basically cargo-audit, except for binaries. 

"Traceable" makes me think of execution tracing, so I don't think that's a good idea for this project. Naming is hard :stuck_out_tongue_closed_eyes:

**Comment by nastevens** [comment]
> Naming is hard

For sure!

> "Traceable" makes me think of execution tracing

 I see what you mean. `rust-traceability` might be a little better but still sort of confusing. What about something like `rust-binaudit`? Still gets the "audit" idea in there but also has a different name from `cargo-audit` as to avoid confusion.
