### ISSUE TITLE
Why do I need to install Visual Studio for using this?

### ISSUE THREAD

**Issue by anshubansal2000** [Shnatsel/rust-audit#25]
I am trying to use this but while trying  to compile, it is asking that I need to install VS. Just wondering why is that?

![image](https://user-images.githubusercontent.com/1768462/94026977-388a3400-fd6f-11ea-904c-9267954f2454.png)

**Comment by anshubansal2000** [comment]
Gotcha. Thanks for the response. I appreciate it. I ended up installing VS
pending reboot which I will do later :) . Out our curiosity, is this
evaluating the Static code analysis or just the simple libraries. I am
trying to do Static Code analysis and following this guide for evaluation
https://analysis-tools.dev/tag/rust

most of the tools are not good. Any recommendations for running SAST.

**Comment by Shnatsel** [comment]
Well, the Rust compiler is already an in-depth static analyzer, so you typically don't need much else. `clippy` can catch some more issues.

See also https://github.com/rust-secure-code/projects
